# _config.yml

# --- Configuración del Sitio ---
title: "Tu Nombre" # Tu nombre completo
name: "Tu Nombre"
description: "Data Scientist | Artificial Inteligence | Python | Advisory | Banking"
url: "https://surzua.github.io" # Tu URL real
baseurl: "" # Déjalo vacío si es un repositorio de usuario

# --- Configuración del Tema (Método Remote Theme) ---
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # Opciones: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# --- Plugins Necesarios ---
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# --- Configuración de Autor (Barra Lateral) ---
author:
  name: "Sebastian Urzúa"
  avatar: "/_assets/img/surzua.jpg" # Sube una foto tuya a esta ruta
  bio: "Científico de Datos apasionado por resolver problemas de negocio mediante Machine Learning e Inteligencia Artificial"
  location: "Santiago, Chile" # O tu ciudad
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/surzuab/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/surzua"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:seb.urzua91@gmail.com"

# --- Ajustes de Lectura ---
locale: "es-ES" # Idioma español
analytics:
  provider: false # Cambia a "google-gtag" si tienes Google Analytics

# --- Valores por defecto para posts ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true